### ISSUE TITLE
Can this app be integrated in my other application?

### ISSUE THREAD

**Issue by haseebehsan** [mesibo/messenger-app-android#1]
Can I integrate this app with my other application which already has users
How can I do it? how can I use users of that application with it (being synced with mesibo user)
any guide for setting my own media server?
Really looking forward for support

Regards

**Comment by mesibo** [comment]
Yes, you can integrate it with your application. 

please refer to tutorials and get-started guide on https://mesibo.com/documentation

**Comment by haseebehsan** [comment]
documentation seems incomplete, can you provide us with latest documentation?

**Comment by transilience** [comment]
the documentation is really incomplete. opened issues and raised tickets but to no avail.

@mesibo kindly respond. we are ready to pay for your services too, however we would be greatful if you can help us understand it better. we would also love to contribute to the documentation if we are able to fully integrate it

**Comment by mesibo** [comment]
https://mesibo.com/documentation/faq/support/#can-you-help-with-messenger-whatsapp-clone-demo
