### ISSUE TITLE
AppID issue

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#15]
What If I have an Android and iOS version of the same app but with different appIds. According to the test I have made, you force a close of the app when the token and appID doesn't match. What can I do in that case? Maybe support for multiple appIds for the same token?

**Comment by mesibo** [comment]
Daniel, This forum is only for the issues in the code and not general technical queries. Please contact contact@mesibo.com for future generic queries 

Coming back to your question, you can generate different token for different appids. For example, we have Android and iOS version of app, both have different appid.

**Comment by danieltigse** [comment]
Oh okay thanks. I will write to you. But I missed something in mi explanation. I want to create different token for different appids for the same user.
