### ISSUE TITLE
What does Mesibo_onConnectionStatus 20 means?

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#18]
My App is just closing for the connection status 20. 
```
public void Mesibo_onConnectionStatus(int var1) {
        Log.wtf("DO THIS", " WHEN string FAILS");
        if (var1 == 1) {
            this.updateSubTitle(this.mMesiboUIOptions.onlineIndicationTitle);
        } else if (var1 == 6) {
            this.updateSubTitle(this.mMesiboUIOptions.connectingIndicationTitle);
        } else if (var1 == 8) {
            this.updateSubTitle(this.mMesiboUIOptions.noNetworkIndicationTitle);
        } else if (var1 == 20) {
            this.getActivity().finish();
        } else {
            this.updateSubTitle(this.mMesiboUIOptions.offlineIndicationTitle);
        }
    }
```
I think you should no finish the app. Maybe a nice toast or something would be better.

**Comment by danieltigse** [comment]
Important fact: I changed my package name from `com.fomatmedical.febo` to `com.fomatmedical.feboapp` and I regenarate the user token with the new appID. It's odd because If I use a user token created with `com.fomatmedical.febo` everything works. I thought you were validation the package name. What am I missing?

**Comment by danieltigse** [comment]
Ok. I found something `STATUS_SHUTDOWN = 20;` but I don't understand why am I receiving that status :(

**Comment by danieltigse** [comment]
Any update in this issue?

**Comment by mesibo** [comment]
are you invoking Mesibo.stop()?

**Comment by danieltigse** [comment]
No. Do I have to?

**Comment by danieltigse** [comment]
Do I need to invoke api for login and logout? I think the answer is yes but. What parameters do I have to  send? 

When I invoke login the code enters in this listener: `Mesibo_onConnectionStatus` with code `Mesibo.STATUS_AUTHFAIL`

**Comment by danieltigse** [comment]
for some reason it only works for users created with appId `com.fomatmedical.febo` but the ones created with `com.fomatmedical.feboapp`

**Comment by danieltigse** [comment]
I am sorry. I changed my package name but not my applicationId inside the build.gradle
