### ISSUE TITLE
I/MesiboJNI: E(0705-191400-027)(7010): *** BUG *** Create client unix socket failed

### ISSUE THREAD

**Issue by kvnramirez** [mesibo/messenger-app-android#26]
With Mesibo STATUS_ONLINE, getting:
I/MesiboJNI: E(0705-191400-027)(7010): *** BUG *** Create client unix socket failed

This happends when I call the method: mesibo.sendMessage(messageParams, msgid, message);

Mesibo needs better documentation, also check: https://github.com/mesibo/samples/issues/21
 
I'm having Issues with android 4.4.2 using mesibo android sdk.

**Comment by mesibo** [comment]
Is this issue also in 4.4.2?

**Comment by karan1213** [comment]
I am receiving this error too, How did you manage to fix this.

**Comment by mesibo** [comment]
Initialize Mesibo from Application and not from activity/fragmenet

**Comment by karan1213** [comment]
But when we authenticate the user to our own server first and then I login user to Mesibo in the background, I had to trigger 'Mesibo Init' method from Login Activity. Although the Actual method is being executed inside the Application class.

I am invoking it like this `getApplication().startMesibo(String accessToken)`
This throws above error and Audio/Video call doesn't get through.

I tried going back to home and restarting app, it still throws the same error untill I kill the app and restrat app. After then it works fine.

**Comment by mesibo** [comment]
Karan, you can initialize Mesibo from App and start whenever you like later. 

For example, 
https://github.com/mesibo/messenger-app-android/blob/master/app/src/main/java/org/mesibo/messenger/SampleAPI.java#L569

As you can see, init function is called from MainApplication which initializes Mesibo and start() much later when the token is obtained. 

Let us know if you still face issues after this change.

**Comment by karan1213** [comment]
Yes, I'm initializing in Application only.

BTW what does `Restart Intent` do?

`Intent restartIntent = new Intent(MainApplication.getRestartIntent());

        Mesibo.runInBackground(MainApplication.getAppContext(), null, restartIntent);`

Is this being used to restart Application?

**Comment by karan1213** [comment]
I noticed that this error occurs in the sample app too. The Audio/Video call doesn't go through some time until I kill the app and restart it after then Call works fine and the exception disappears too.

**Comment by mesibo** [comment]
Can you try the Google Play store version too and let us know if you can reproduce. I am anyway raising this with development team .

**Comment by mesibo** [comment]
1) Are you seeing this also in your log "**_Unix server sock failed:_**"
2) Can you try the Google Play store version too and let us know if you can reproduce. 

I am anyway raising this with the development team.

**Comment by karan1213** [comment]
1. Logs show two kinds of exceptions

```
*** BUG *** openssl session management not implemented

 *** BUG *** Create client unix socket failed: /data/user/0/<packagename>/Mesibo/usock
```

2. Yes, the issue exists in Play store version as well. I have tried this on Nokia 8.1 (Android 9.0) device.

**Comment by mesibo** [comment]
Please update to the latest version and see if "Create client unix socket failed:" is resolved. Disregard openssl log for now.

**Comment by karan1213** [comment]
Yeah updated SDK to `implementation 'com.mesibo.api:mesibo:1.0.80'`
And working fine now. Thanks!

**Comment by maddenbrain** [comment]
Have this logs on version 'com.mesibo.api:mesibo:1.0.90'.

**Comment by mesibo** [comment]
It is not possible as that is fixed a long back and that text was entirely removed. You MUST be using an old API.

**Comment by maddenbrain** [comment]
But I have these logs.
Maybe I'm using mesibo in a wrong way?
How can I contact your support? Any live chat?

**Comment by mesibo** [comment]
Certainly! You can reach us here http://mesibo.com/ticket
