### ISSUE TITLE
Send button not enabled

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#3]
I am trying to chat with some user that is registered as user in the dashboard but:
1. When I use this line: `MesiboUI.launchMessageView(context, "pedro_aim@gmail.com", 0)` the Message View doesn't open. But If I send a message from the dashboard and then use the line again the Message View opens.
2. When the message View opens I can send messages because the send button doesn't appear.
![whatsapp image 2019-02-01 at 1 04 15 pm](https://user-images.githubusercontent.com/1870723/52140861-e9cfd980-2621-11e9-9eb2-3208c37dd662.jpeg)

**Comment by mesibo** [comment]
Can you add file transfer handler and see if that resolves. The UI hides file camera button when file transfer handler is not present and in the process, even send button is gone. 

We will fix it but in the meantime, please add file transfer handler

**Comment by danieltigse** [comment]
You are right! That answers me my second question. What about the first one? Why do I have to send a message from the console to make the message view get open?

**Comment by mesibo** [comment]
Daniel,

1) MessagingFragment tries to find the user or group profile and closes if none is found. You can either create a user/group profile before launching OR pass a fragment argument `createprofile` as true. 

2) latest version fixes the 2nd issue!
