### ISSUE TITLE
Wrong User status inside console

### ISSUE THREAD

**Issue by karan1213** [mesibo/messenger-app-android#31]
When I look inside the console, I see more than 200 concurrent users which is not correct.
I know because I am managing the online users on my server as well.

I think when a user comes online, it gets recorded and if the device gets offline then that user's status does not get updated until he comes online again. And this is adding up concurrent users count inside the console stats.

Let me know the correct reason if I am wrong.
If I am correct, Do you have any plans to fix this?
Will this affect the free tier limit?

_If I have raised the issue at the wrong place, let me know I'll move to correct place._

**Comment by mesibo** [comment]
Can you share the screenshot of the console and the app id? Mask all confidential information or email us at contact@mesibo.com.

**Comment by karan1213** [comment]
Sent

**Comment by mesibo** [comment]
replied over email. Not reproducible.
