### ISSUE TITLE
How can I change text on Audio/Video calling screen?

### ISSUE THREAD

**Issue by rashidafzaal** [mesibo/messenger-app-android#37]
How can I change text on Audio/Video calling screen? It always says **"Mesibo Video call"**

As far as, I observed the code, I think we can't do that as the project is using decompiled classes and that **"mesibo video call"** text is inside that. 

Is there any way to change?

**Comment by mesibo** [comment]
Yes, you can change it in MesiboCallConfig

**Comment by rashidafzaal** [comment]
There is no such file, not even in whole project. Look at this: http://prntscr.com/ojeda3

**Comment by mesibo** [comment]
`MesiboCallConfig config = MesiboCall.getConfig`

You can modify config to suit your need. No need to set config. 

Let me know if you still having issues.

**Comment by rashidafzaal** [comment]
I can't edit the `MesiboCallConfig` 
How to set the text? where to change it. There is nothing like this in `MesiboCallConfig`

**Comment by mesibo** [comment]
We have uploaded a beta version here https://github.com/mesibo/messenger-app-android-beta which will allow you to customize every aspect of the app - messaging, audio and video calling screens. For example, look here for customizing video calling UI

https://github.com/mesibo/messenger-app-android-beta/blob/master/app/src/main/java/org/mesibo/messenger/VideoCallFragment.java

**Comment by rashidafzaal** [comment]
Thanks much
