### ISSUE TITLE
Account Kit is deprecated.  how to replace it?

### ISSUE THREAD

**Issue by uguer** [mesibo/messenger-app-android#42]
from 9 September 2019 facebook account kit is deprecated.  How to create an alternative?

**Comment by tru247** [comment]
Hello Team Mesibo. Since the Facebook account kit is depreciation what's the way forward?

**Comment by mesibo** [comment]
Folks, mesibo has **no dependency or association** with AccountKit. 

AccountKit was merely used in the sample app code for the demonstration purpose. You can replace the code with your own implementation. There are plenty of SMS providers that you can use. We will also update sample code after removing the account kit.

**Comment by tru247** [comment]
Thanks for the update. I propose the use of Infobip push notifications implementation. What do you guys think?

**Comment by uguer** [comment]
it could be fine.  when do you update it?

**Comment by tru247** [comment]
I finally hacked a way around this issue with another SMS API.

**Comment by uguer** [comment]
I finally hacked a way around this issue with another SMS API.



> Il giorno 14 nov 2019, alle ore 04:31, C.E.O. Otieno <notifications@github.com> ha scritto:
> 
> I finally hacked a way around this issue with another SMS API.
>

**Comment by uguer** [comment]
do we find it at download?

**Comment by lena-abarova** [comment]
> I finally hacked a way around this issue with another SMS API.

how did you pass that SMS?

**Comment by mesibo** [comment]
You need to use your own SMS provider or use unverified login for testing. We plan to release a new demo with anonymous login shortly.
