### ISSUE TITLE
Mesibo Status Code 6 and then 9

### ISSUE THREAD

**Issue by sidhuparas** [mesibo/messenger-app-android#48]
Hi,
 
Following is my code setup:

```
val api = Mesibo.getInstance()
            api.init(requireContext().applicationContext)
            Mesibo.initCrashHandler(this)

            Mesibo.setPath(Environment.getExternalStorageDirectory().absolutePath)
            Mesibo.addListener(this)
            Mesibo.setAccessToken(mesiboAccessToken)
            Mesibo.setSecureConnection(true)

            Mesibo.start()
```

In the logs, first I get a status code of 6 which means connecting and afterwards I get 9 which is calling is muted. I don't use calling whatsoever so doesn't matter but I am not getting any status code afterwards. If something is wrong on my end, at least something should happen like failure case. Can you clarify what's wrong?

PS. In the Mesibo dashboard, last seen of the user gets changed to the instance when above code is executed but then that remains static unless I restart the app.

**Comment by mesibo** [comment]
Hello, error 9 is related to on-premise. It seems like you have configure on-premise but your server is not running. Either you can run the on-premise server or disable on-premise and try again.

**Comment by sidhuparas** [comment]
@mesibo Thanks for quick response. Let me check.
