### ISSUE TITLE
How to change account kit?

### ISSUE THREAD

**Issue by Godzilla912** [mesibo/messenger-app-android#59]
is their any territorial for it_

**Comment by mesibo** [comment]
where do you see account kit?

**Comment by Godzilla912** [comment]
After compile the otp code will not get automatically. Even playstor
orginal apk.

**Comment by mesibo** [comment]
Host the backend and use your own OTP provider, we will not send OTP.

**Comment by Godzilla912** [comment]
Oky thnk you sir.
