### ISSUE TITLE
How to config demo app to mesibo server

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-android#63]
Here I am working to set up a Mesibo for the android users in Mesibo's own server, But here I am facing some issues and I do not know that how to overcome those. So can you please help me out?

I have done PHP set-up and I also upgraded those PHP files. In the PHP file, I also have created DB and done the configuration part. I also configured Master key and APP configurations.

But when I check then I am not getting API response properly and due to this it is not been connected with android, So what should I do for this please help. I should also do APP token set-up on the android side? and if yes then where should I do this APP token Setup in android?

**Comment by mesibo** [comment]
Have you tried get-started or have you directly started on messenger code?
