### ISSUE TITLE
Issue in Messages sending & receiving and Chat list is not coming

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-android#64]
I have set up Mesibo Android App & Backend Setup properly, All things are running smoothly but after I message someone then Message are not sending and recant chats are not coming in the list and chat screen, also group chats message saw delivery but not received by group members.
What should I do next?? Bcoz I already Check all my backend error_logs, no issues from there, Also I checked the app side.

To check my Mesibo Consol: messaging.apps.developer@gmail.com <- this email is I am using for Mesibo consol
This is my backend API URL: https://streitmen.com/Mesibo-App/api.php

also i am facing this error 
[27-May-2021 16:48:12 UTC] other: implode(): Passing glue string after array is deprecated. Swap the parameters in /home/u791210233/domains/streitmen.com/public_html/Mesibo-App/mysqlidb.php on line 1782

[WhatsApp Image 2021-05-27 at 10 02 53 PM](https://user-images.githubusercontent.com/36466968/119863568-5380f980-bf37-11eb-8243-14820c647eb2.jpeg)

![WhatsApp Image 2021-05-27 at 10 00 35 PM](https://user-images.githubusercontent.com/36466968/119863273-02710580-bf37-11eb-92f7-a9e3b9e5c833.jpeg)
![WhatsApp Image 2021-05-27 at 9 59 37 PM](https://user-images.githubusercontent.com/36466968/119863281-043ac900-bf37-11eb-8492-820bf10326f1.jpeg)

**Comment by mesibo** [comment]
most likely incorrect configuration. have you tried the mesibo first app or have you directly started with messenger? 

Before using the messenger code or UI modules, we expect you to read and build the First App tutorial for the platform of your choice, it explains and demonstrates how to send messages and make calls in just a few lines of code. Please visit the link below for the same.

https://mesibo.com/documentation/tutorials/get-started/ 

We will be happy to help you with the messenger or UI modules after you have successfully used the first app.

**Comment by nishantmonapara** [comment]
Yeah that issue is been solved, But Now I am facing another issue, Please see below log errors.

Implode(): Passing glue string after the array is deprecated. Swap the parameters in /home/u791210233/domains/streitmen.com/public_html/Mesibo-App/mysqlidb.php on line 1782

Now the issue is that in the chat list If I do some chats then after the chat completes and the screen refreshes the chat list is not showing.

Till the time I do chats and I am on the same screen, I can see recent messages and chats with the same person, But as soon as I go back and open the app again then there will be no message to the same person in the chat room and also all things are gone from chat list


--->I checked all APIs are calling properly, Issue is when mail data is fetched.

https://user-images.githubusercontent.com/36466968/119873341-140bda80-bf42-11eb-8c14-b7b1204bdda4.mp4

**Comment by nishantmonapara** [comment]
Hi @mesibo have you checked?

**Comment by mesibo** [comment]
It happens when the database is not set. If you are using Android 10, ensure that you are NOT calling Mesibo.setPath() API with external storage.  Use android:requestLegacyExternalStorage="true" as approproate.

We will not check the code as messenger is going through a major update and will be released in 2 weeks. If any doubt, use the first app tutorial to understand more.

**Comment by nishantmonapara** [comment]
![WhatsApp Image 2021-05-29 at 3 44 25 PM](https://user-images.githubusercontent.com/36466968/120066928-8db4dd00-c096-11eb-9d18-ab1739270a26.jpeg)
![WhatsApp Image 2021-05-29 at 3 41 12 PM](https://user-images.githubusercontent.com/36466968/120066931-8f7ea080-c096-11eb-812a-b20ed0d5e8a2.jpeg)

**Comment by mesibo** [comment]
Please run the first app and try to reproduce it. We will be happy to helo but if you ignore our suggestions to use the first app, we will be unable to help.
