### ISSUE TITLE
Unable to change mesibo text in Call Screen

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-android#65]
![WhatsApp Image 2021-06-25 at 4 36 53 PM](https://user-images.githubusercontent.com/36466968/123415965-9afcb300-d5d3-11eb-9d53-a817058f0728.jpeg)
Hi Mesibo Team.
I am Unable to change mesibo text in Call Screen, I have Atteched it.
Please help me with this,

Thanks,
Nishant

![WhatsApp Image 2021-06-25 at 4 34 34 PM](https://user-images.githubusercontent.com/36466968/123415738-52dd9080-d5d3-11eb-9ce4-ec55717da268.jpeg)

**Comment by nishantmonapara** [comment]
Hey Mesibo Team,
Any Updates for me??

Waiting for your response.
Thanks,
Nishant

**Comment by mesibo** [comment]
https://mesibo.com/documentation/faq/support/#what-is-the-sla-for-issue-resolution
