### ISSUE TITLE
new Mesibo version is breaking my app

### ISSUE THREAD

**Issue by AzamudinUMCH** [mesibo/messenger-app-android#66]
<com.mesibo.calls.ImageTouchSlider
                    android:id="@+id/slider"
                    android:layout_width="wrap_content"
                    android:layout_height="@dimen/_70sdp"
                    android:gravity="left" />
                    
              as you can see, this library cannot be found anymore and i dont know what to replace

**Comment by mesibo** [comment]
Refer to the link below to know what information we require to help you effectively.

https://mesibo.com/documentation/faq/support/#what-information-should-i-provide-when-requesting-technical-support
