### ISSUE TITLE
Suddenly my app code running stopped  

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-android#67]
Hi @mesibo Team

I have complete the whole app from my side and One last changes remain so I have open Android studio for changes the code but suddenly I have an issue with *Mesibo.UserProfileUpdateListener* there are some errors from @mesibo,
So please check and let me know how to solve this,

Thanks,
Nishant.

![WhatsApp Image 2021-07-10 at 10 38 48 AM](https://user-images.githubusercontent.com/36466968/125152597-1da47700-e16b-11eb-8cd3-482b847ed725.jpeg)
![WhatsApp Image 2021-07-10 at 10 40 27 AM](https://user-images.githubusercontent.com/36466968/125152611-4298ea00-e16b-11eb-85b8-1b6933aca439.jpeg)

**Comment by mesibo** [comment]
You are using the old code with the latest APIs. Update code or use the older API versions.

Multiple emails have been sent to your users on API updates and changes.
