### ISSUE TITLE
User Online offline status issue

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-android#68]
Hi @mesibo team,
I have setup Back-end and New Android code,
Suddenly i am facing issue of user online & offline status,
Also i have downloaded mesibo demo app from playstore and checked but same issue found.

Please let me know How to figure it out.

Thanks.
Nishant.

**Comment by mesibo** [comment]
The ticket is closed as it has no info.

Use code and proper elaboration to explain your problems else we will close ticketss
