### ISSUE TITLE
Upgrade targetSdkVersion to Android 14

### ISSUE THREAD

**Issue by ekoo** [mesibo/messenger-app-android#74]
Based on Google Play Requirement [Target SDK](https://developer.android.com/google/play/requirements/target-sdk), please make this app support for SDK 34 / Android 14, I tried to upgrade manually but some function didn't work, like file picker etc

**Comment by mesibo** [comment]
Closing due to insufficient details.

Be precise with logs and code snippets about any issues.

**Comment by mesibo** [comment]
Updated permission handling for Andorid 14

Please update the API to v2.4.1 and the messenger code. Please report if any issues.
