### ISSUE TITLE
Messages and conversations are not stored

### ISSUE THREAD

**Issue by danieltigse** [mesibo/messenger-app-android#9]
When I receive new messages in the message list, I tap on the new message, the message view is opened but there is not messages, it's empty. And when I go back from the message view, the message list is empty.

I am calling `Mesibo.setDatabase` after `Mesibo.setAccessToken` 

Am I missing something?

**Comment by mesibo** [comment]
This indicates that the database is not set. Can you share the code snippet where you are setting database?

**Comment by danieltigse** [comment]
From my `Application()` I am calling:
```java
Mesibo api = Mesibo.getInstance();
api.init(context);
MesiboApi.startMesibo("xxx");
```

And `MesiboApi.startMesibo` is implemented in this way:
```
public static boolean startMesibo(String token) {

        mToken = token;

        MesiboRegistrationIntentService.startRegistration(mContext, "1546744701869", MesiboListeners.getInstance());
        // set path for storing DB and messaging files
        Mesibo.setPath(Environment.getExternalStorageDirectory().getAbsolutePath());

        // add lister
        Mesibo.addListener(MesiboListeners.getInstance());
        MesiboCall.getInstance().setListener(MesiboListeners.getInstance());

        // add file transfer handler
        MesiboFileTransferHelper fileTransferHelper = new MesiboFileTransferHelper();
        Mesibo.addListener(fileTransferHelper);

        // this will also register listener from the constructor
        mNotifyUser = new NotifyUser(FeboApplication.Companion.getAppContext());

        // set access token
        if(0 != Mesibo.setAccessToken(mToken)) {
            return false;
        }

        Mesibo.setDatabase("mesibo.db", 0);

        // Now start mesibo
        if(0 != Mesibo.start()) {
            return false;
        }

        Intent restartIntent = new Intent(FeboApplication.Companion.getRestartIntent());

        Mesibo.runInBackground(FeboApplication.Companion.getAppContext(), null, restartIntent);

        return true;
    }
```

**Comment by danieltigse** [comment]
For some reason the function `Mesibo.setDatabase` returns false. I debugged the implementation of this function and enters in this condition
```
if (0 != c.set_database(dbNameWithPath)) {
      return false;
}
```

**Comment by mesibo** [comment]
This should happen only if the path is wrong or the permission was denied. Ensure that your application has WRITE_EXTERNAL_STORAGE. This is a run-time permission and hence you must ask for it during run-time.  

Alternatively, you can remove this line:

    Mesibo.setPath(Environment.getExternalStorageDirectory().getAbsolutePath());

**Comment by danieltigse** [comment]
Ok my bad. It was all about permissions. But I instead removed the line you mentioned. I asume you store the data in the space reserved for the app, not in the external storage.
